name: 'Github Bump and Tag'
description: 'Github action to bump the patch version and tag'
author: 'Lydian'
inputs:
  token:
    description: 'GitHub token for pushing tags'
    required: true
runs:
  using: 'docker'
  image: Dockerfile
outputs:
  currentVersion:
    description: 'Current highest version tag'
  newVersion:
    description: 'The newly calculated version'
branding:
  icon: 'git-merge'
  color: 'purple'
